# Generated by Django 5.2.12 on 2026-04-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_chatparticipant_last_read_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatparticipant',
            name='role',
            field=models.CharField(choices=[('teacher', 'Преподаватель'), ('student', 'Студент'), ('admin', 'Администратор')], max_length=10, verbose_name='Роль в чате'),
        ),
    ]
