# Generated by Django 5.2.12 on 2026-04-09 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroupthrough',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentgroups',
            name='students',
            field=models.ManyToManyField(related_name='study_groups', through='groups.StudentGroupThrough', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherattachment',
            name='group_assignment',
            field=models.ForeignKey(limit_choices_to=models.Q(('course__course_type', 'full')), on_delete=django.db.models.deletion.CASCADE, to='groups.coursegroupattachment'),
        ),
        migrations.AddField(
            model_name='teacherattachment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
        migrations.AddField(
            model_name='teacherattachment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to=models.Q(('account_type', 'teacher')), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='coursegroupattachment',
            constraint=models.UniqueConstraint(fields=('group', 'course'), name='unique_course_group'),
        ),
        migrations.AddConstraint(
            model_name='teacherattachment',
            constraint=models.UniqueConstraint(fields=('group_assignment', 'teacher', 'subject'), name='unique_subject_teacher_course_group'),
        ),
    ]
