# Generated by Django 5.2.12 on 2026-04-12 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_assignment_submission_file'),
        ('groups', '0002_initial'),
        ('universities', '0005_appearance_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroups',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='universities.university', verbose_name='ВУЗ'),
        ),
        migrations.AlterField(
            model_name='studentgroups',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='studentgroups',
            constraint=models.UniqueConstraint(fields=('university', 'name'), name='uq_group_university_name'),
        ),
    ]
