# Generated by Django 5.2.12 on 2026-04-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_semester_schedule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='semesterscheduleentry',
            new_name='groups_seme_schedul_12afea_idx',
            old_name='groups_semes_schedule_3d0b1a_idx',
        ),
    ]
