# Generated by Django 5.2.12 on 2026-04-26 14:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_course_uq_course_university_title_and_more'),
        ('groups', '0008_group_null_university_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursegroupattachment',
            options={'verbose_name': 'Привязка курса к группе', 'verbose_name_plural': 'Привязки курсов к группам'},
        ),
        migrations.AlterModelOptions(
            name='semesterschedule',
            options={'verbose_name': 'Расписание семестра', 'verbose_name_plural': 'Расписания семестров'},
        ),
        migrations.AlterModelOptions(
            name='semesterscheduleentry',
            options={'verbose_name': 'Ячейка расписания', 'verbose_name_plural': 'Ячейки расписания'},
        ),
        migrations.AlterModelOptions(
            name='studentgroups',
            options={'verbose_name': 'Группа студентов', 'verbose_name_plural': 'Группы студентов'},
        ),
        migrations.AlterModelOptions(
            name='studentgroupthrough',
            options={'verbose_name': 'Участник группы', 'verbose_name_plural': 'Участники групп'},
        ),
        migrations.AlterModelOptions(
            name='teacherattachment',
            options={'verbose_name': 'Привязка преподавателя к предмету', 'verbose_name_plural': 'Привязки преподавателей к предметам'},
        ),
        migrations.AlterField(
            model_name='coursegroupattachment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='coursegroupattachment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.studentgroups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='semesterschedule',
            name='break_minutes',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Перерыв (мин.)'),
        ),
        migrations.AlterField(
            model_name='semesterschedule',
            name='breaks_minutes',
            field=models.JSONField(blank=True, default=list, verbose_name='Перерывы по парам (мин.)'),
        ),
        migrations.AlterField(
            model_name='semesterschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='semesterschedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_schedules', to='groups.studentgroups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='semesterschedule',
            name='lesson_duration_minutes',
            field=models.PositiveSmallIntegerField(default=90, verbose_name='Длительность пары (мин.)'),
        ),
        migrations.AlterField(
            model_name='semesterschedule',
            name='lessons_per_day',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Количество пар в день'),
        ),
        migrations.AlterField(
            model_name='semesterschedule',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_schedules', to='courses.semester', verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='semesterschedule',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='semesterschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='semesterscheduleentry',
            name='lesson',
            field=models.PositiveSmallIntegerField(verbose_name='Номер пары'),
        ),
        migrations.AlterField(
            model_name='semesterscheduleentry',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='groups.semesterschedule', verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='semesterscheduleentry',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='courses.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='semesterscheduleentry',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='semesterscheduleentry',
            name='weekday',
            field=models.PositiveSmallIntegerField(verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='studentgroups',
            name='courses',
            field=models.ManyToManyField(related_name='bind_groups', through='groups.CourseGroupAttachment', to='courses.course', verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='studentgroups',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='studentgroups',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studentgroups',
            name='students',
            field=models.ManyToManyField(related_name='study_groups', through='groups.StudentGroupThrough', to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
        migrations.AlterField(
            model_name='studentgroups',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='studentgroupthrough',
            name='enrolled_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата зачисления'),
        ),
        migrations.AlterField(
            model_name='studentgroupthrough',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.studentgroups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='studentgroupthrough',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='teacherattachment',
            name='group_assignment',
            field=models.ForeignKey(limit_choices_to=models.Q(('course__course_type', 'full')), on_delete=django.db.models.deletion.CASCADE, to='groups.coursegroupattachment', verbose_name='Привязка курса к группе'),
        ),
        migrations.AlterField(
            model_name='teacherattachment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='teacherattachment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to=models.Q(('account_type', 'teacher')), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
    ]
