# Generated by Django 5.2.12 on 2026-05-07 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_course_uq_course_university_title_and_more'),
        ('groups', '0009_alter_coursegroupattachment_options_and_more'),
        ('universities', '0005_appearance_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentgroups',
            name='uq_group_university_name',
        ),
        migrations.RemoveConstraint(
            model_name='studentgroups',
            name='uq_group_nulluniversity_name',
        ),
        migrations.AddConstraint(
            model_name='studentgroups',
            constraint=models.UniqueConstraint(fields=('university', 'name'), name='uq_group_university_name_v2', nulls_distinct=False),
        ),
    ]
