# Generated by Django 5.2.12 on 2026-04-12 20:09

import django.core.files.storage
import pathlib
import users.models
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_appearance_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesprofile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/osnova/protected_files')), upload_to=users.models.student_file_upload_to, validators=[users.validators.validate_file_size]),
        ),
    ]
