# Generated by Django 5.2.12 on 2026-04-26 14:41

import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
import pathlib
import users.models
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_role_null_university_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filesprofile',
            options={'verbose_name': 'Файл профиля', 'verbose_name_plural': 'Файлы профиля'},
        ),
        migrations.AlterModelOptions(
            name='permissionaction',
            options={'ordering': ('module__position', 'position', 'id'), 'verbose_name': 'Действие', 'verbose_name_plural': 'Действия'},
        ),
        migrations.AlterModelOptions(
            name='permissionmodule',
            options={'ordering': ('position', 'id'), 'verbose_name': 'Модуль прав', 'verbose_name_plural': 'Модули прав'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('name', 'id'), 'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ('role_id', 'permission__module__position', 'permission__position', 'id'), 'verbose_name': 'Разрешение роли', 'verbose_name_plural': 'Разрешения ролей'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='filesprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='filesprofile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/osnova-main/osnova/protected_files')), upload_to=users.models.student_file_upload_to, validators=[users.validators.validate_file_size], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='filesprofile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='filesprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='filesprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[users.validators.validate_is_student], verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='permissionaction',
            name='code',
            field=models.CharField(max_length=150, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='permissionaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='permissionaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='permissionaction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='permissionaction',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='users.permissionmodule', verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='permissionaction',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='permissionaction',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='permissionaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='permissionmodule',
            name='allow_partial_permissions',
            field=models.BooleanField(default=True, verbose_name='Разрешать частичные права'),
        ),
        migrations.AlterField(
            model_name='permissionmodule',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='permissionmodule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='permissionmodule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='permissionmodule',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='permissionmodule',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='permissionmodule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Системная'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='users.RolePermission', to='users.permissionaction', verbose_name='Права'),
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=170, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='users.permissionaction', verbose_name='Разрешение'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('owner', 'Главный пользователь'), ('university_owner', 'Владелец университета'), ('employee', 'Сотрудник'), ('teacher', 'Учитель'), ('student', 'Учащийся')], db_index=True, default='student', max_length=20, verbose_name='Тип аккаунта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_avatar_upload_to, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Определяет, считается ли пользователь активным. Отключайте это вместо удаления аккаунта.', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Определяет, может ли пользователь входить в административную часть сайта.', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Требуется смена пароля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role', verbose_name='Роль'),
        ),
    ]
