# Generated by Django 5.2.12 on 2026-04-09 09:40

import universities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=universities.models.banner_image_upload_to, verbose_name='Изображение (16:3)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='Используется в URL: domain.com/api/<slug>/...', max_length=270, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=universities.models.university_logo_upload_to)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Дата окончания срока использования ВУЗа. Информационное поле.', null=True, verbose_name='Срок использования')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ВУЗ',
                'verbose_name_plural': 'ВУЗы',
                'ordering': ('name',),
            },
        ),
    ]
