# Generated by Django 5.2.12 on 2026-04-09 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_banners', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил'),
        ),
        migrations.AddField(
            model_name='university',
            name='owner',
            field=models.ForeignKey(help_text='Пользователь с полным доступом к данному ВУЗу.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_universities', to=settings.AUTH_USER_MODEL, verbose_name='Управляющий'),
        ),
        migrations.AddField(
            model_name='banner',
            name='university',
            field=models.OneToOneField(blank=True, help_text='NULL = глобальный баннер для всего проекта', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='universities.university', verbose_name='ВУЗ'),
        ),
        migrations.AddConstraint(
            model_name='banner',
            constraint=models.UniqueConstraint(condition=models.Q(('university__isnull', False)), fields=('university',), name='uq_banner_university'),
        ),
        migrations.AddConstraint(
            model_name='banner',
            constraint=models.UniqueConstraint(condition=models.Q(('university__isnull', True)), fields=('id',), name='uq_banner_global_singleton'),
        ),
    ]
