# Generated by Django 5.2.12 on 2026-04-11 11:11

import universities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_universitydocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitydocument',
            name='file',
            field=models.FileField(upload_to=universities.models.document_file_upload_to),
        ),
    ]
