# Generated by Django 5.2.12 on 2026-04-09 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.assignment'),
        ),
        migrations.AddField(
            model_name='grade',
            name='graded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_grades', to=settings.AUTH_USER_MODEL, verbose_name='Кто выставил'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course'),
        ),
        migrations.AddField(
            model_name='lecturematerial',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_data', to='courses.material'),
        ),
        migrations.AddField(
            model_name='documentmaterial',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_data', to='courses.material'),
        ),
        migrations.AddField(
            model_name='materialfile',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.material'),
        ),
        migrations.AddField(
            model_name='materialfolder',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='courses.material'),
        ),
        migrations.AddField(
            model_name='materialfolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.materialfolder'),
        ),
        migrations.AddField(
            model_name='materialfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.materialfolder'),
        ),
        migrations.AddField(
            model_name='presentationmaterial',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_data', to='courses.material'),
        ),
        migrations.AddField(
            model_name='semester',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='courses.course'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='courses.studentgroup'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='courses.semester'),
        ),
        migrations.AddField(
            model_name='material',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.subject'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.subject'),
        ),
        migrations.AddField(
            model_name='subjectteacher',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='courses.subject'),
        ),
        migrations.AddField(
            model_name='subjectteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testmaterial',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_data', to='courses.material'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.testmaterial'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.testmaterial'),
        ),
        migrations.AddField(
            model_name='testansweroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.testquestion'),
        ),
        migrations.AddField(
            model_name='teststudentanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.testattempt'),
        ),
        migrations.AddField(
            model_name='teststudentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='courses.testquestion'),
        ),
        migrations.AddField(
            model_name='teststudentanswer',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='courses.testansweroption'),
        ),
        migrations.AddField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_topics', to='courses.course'),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.subject'),
        ),
        migrations.AddField(
            model_name='material',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.topic'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_type', 'is_active'], name='courses_cou_course__a77db8_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('university', 'title'), name='uq_course_university_title'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('university', 'slug'), name='uq_course_university_slug'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='uq_grade_assignment_student'),
        ),
        migrations.AddConstraint(
            model_name='materialfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('material', 'title'), name='uq_root_folder_title'),
        ),
        migrations.AddConstraint(
            model_name='materialfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'title'), name='uq_child_folder_title'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('course', 'title'), name='uq_semester_course_title'),
        ),
        migrations.AddConstraint(
            model_name='studentgroup',
            constraint=models.UniqueConstraint(fields=('course', 'title'), name='uq_student_group_course_title'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='uq_enrollment_student_course'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('semester', 'title'), name='uq_subject_sem_title'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('subject', 'title'), name='uq_assignment_subject_title'),
        ),
        migrations.AddConstraint(
            model_name='subjectteacher',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject'), name='uq_subject_teacher'),
        ),
        migrations.AddConstraint(
            model_name='teststudentanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uq_attempt_question'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('subject__isnull', True)), models.Q(('course__isnull', True), ('subject__isnull', False)), _connector='OR'), name='topic_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('course', 'title'), name='uq_topic_course_title'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(condition=models.Q(('subject__isnull', False)), fields=('subject', 'title'), name='uq_topic_subject_title'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['material_type', 'is_published'], name='courses_mat_materia_fb52c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('subject__isnull', True), ('topic__isnull', True)), models.Q(('course__isnull', True), ('subject__isnull', False), ('topic__isnull', True)), models.Q(('course__isnull', True), ('subject__isnull', True), ('topic__isnull', False)), _connector='OR'), name='material_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('course', 'title'), name='uq_mat_course_title'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('subject__isnull', False)), fields=('subject', 'title'), name='uq_mat_subject_title'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('topic__isnull', False)), fields=('topic', 'title'), name='uq_mat_topic_title'),
        ),
    ]
