# Generated by Django 5.2.12 on 2026-04-09 00:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
        ('universities', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStoreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('image', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, max_length=64)),
                ('duration', models.CharField(blank=True, max_length=64)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('content_folder_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_card', to='courses.course')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_store_cards', to='universities.university', verbose_name='ВУЗ')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='coursestorecard',
            constraint=models.UniqueConstraint(fields=('university', 'title'), name='uq_course_store_card_university_title'),
        ),
    ]

