# Generated by Django 5.2.12 on 2026-04-16 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_assignment_max_grade_default_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='max_grade',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальный балл'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('full', 'Высшее образование'), ('simple', 'Дополнительное образование')], max_length=10),
        ),
    ]
