# Generated by Django 5.2.12 on 2026-04-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_null_university_unique'),
        ('universities', '0005_appearance_models'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='course',
            name='uq_course_university_title',
            constraint=models.UniqueConstraint(fields=('university', 'title'), name='uq_course_university_title', violation_error_message='Курс с таким названием уже существует.'),
        ),
        migrations.AlterConstraint(
            model_name='course',
            name='uq_course_nulluniversity_title',
            constraint=models.UniqueConstraint(condition=models.Q(('university__isnull', True)), fields=('title',), name='uq_course_nulluniversity_title', violation_error_message='Курс с таким названием уже существует.'),
        ),
    ]
